### ISSUE TITLE
Mais informações no README

### ISSUE THREAD

**Issue by vitordevsp** [GustavoSMelo/PokeSearch#2]
Olá Gustavo, estava olhando seu GitHub e achei esse projeto bem legal, não manjo de react-native, vou iniciar meus estudos essa semana, mas queria recriar esse projeto, vou clonar ele depois pra entender como vc fez e qual API usou.

Gostaria de dar uma dica só pra manter mais informações sobre o projeto no README, talvez alguns prints tbm ficaria show.

Parabéns pelos projetos, vou dar uma olhada em outros depois.

**Comment by GustavoSMelo** [comment]
> Olá Gustavo, estava olhando seu GitHub e achei esse projeto bem legal, não manjo de react-native, vou iniciar meus estudos essa semana, mas queria recriar esse projeto, vou clonar ele depois pra entender como vc fez e qual API usou.
> 
> Gostaria de dar uma dica só pra manter mais informações sobre o projeto no README, talvez alguns prints tbm ficaria show.
> 
> Parabéns pelos projetos, vou dar uma olhada em outros depois.

Olá, Primeiramente gostaria de agradecer por ter se interessado em um dos meus projetos.
Esse projeto em especifico foi meu primeiro app usando React Native, e como o codigo desse projeto ta bem feio e não está seguindo nenhum design pattern, optei em não dar tanta atenção assim, por isso ele não está na pagina inicial do meu github. 

Agradeço sua sugestão, e futuramente irei atualizar e dar a devida atenção à esse projeto.

Caso precise de algo, ou tenha dificuldade em seus estudos, pode contar comigo para lhe ajudar :)

**Comment by vitordevsp** [comment]
Show Gustavo, eu também tinha alguns projetos mais antigos assim, acho que te adicionei no Linkedin e estou seguindo seu perfil aqui, qualquer coisa entro em contato sim, valeu ;)
